#!/bin/sh

# Get the actual sink
sink=`/usr/bin/pacmd dump  | grep set-default-sink | cut -f 2 -d ' '`
# Get the current mute status
ismuted=`/usr/bin/pacmd dump | grep set-sink-mute | cut -f 3 -d ' '`

# If the sound is muted
if [ $ismuted = "yes" ]
then
	# Unmute the sound
	/usr/bin/pactl set-sink-mute $sink 0
fi

# Change the volume
case $1 in
	inc)
		/usr/bin/pactl -- set-sink-volume $sink '+5%'
	;;
	dec)
		/usr/bin/pactl -- set-sink-volume $sink '-5%'
	;;
	*)
		echo "Usage: $0 (inc|dec)" 1>&2
	;;
esac
