#!/bin/sh

sink=`/usr/bin/pacmd dump  | grep set-default-sink | cut -f 2 -d ' '`

case $1 in
	inc)	pactl -- set-sink-volume $sink '+5%' ;;
	dec)	pactl -- set-sink-volume $sink '-5%' ;;
	*)		echo "Usage: $0 (inc|dec)" 1>&2 ;;
esac
